version: '3.3'

services:
    php-fpm:
        container_name: php-fpm
        build: ./
        ports:
            - '5000:8000'
        volumes:
            - ./:/var/www/html
        depends_on:
            - database

    database:
        image: mariadb:10.6.3
        command: --default-authentication-plugin=mysql_native_password
        #restart: always
        environment:
            MYSQL_ROOT_PASSWORD: root
            MYSQL_DATABASE: test
